# name: Docker Image CI
#
# on:
#   push:
#     branches: [ master ]
#
# jobs:
#
#   build:
#
#     runs-on: ubuntu-latest
#
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: |
#         export PYTHONPATH=$(pwd)
#         export VERSION=$(python3 -c "import server; print(server.__version__)")
#         docker build -t docker.pkg.github.com/hadar-simulator/community-server/server:$VERSION -f deploy/Dockerfile .
#         docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $TOKEN
#         docker push docker.pkg.github.com/hadar-simulator/community-server/server:$VERSION
#       env:
#         TOKEN: ${{ secrets.GITHUB_TOKEN }}
#